### PR TITLE
Updating to allow override of base Image for lambda GraalVM

### PR DESCRIPTION
**Pull request by runscinch**

### CODE REVIEW

**Comment by runscinch** [comment]
Related to this issue: https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/279

This change would allow the base image to be updated from default for Lambda runtime.

**Review by melix — COMMENTED** [review]
Would you mind adding a test for this?

**Comment by runscinch** [comment]
@melix sure, would you prefer I create a new class or add to an existing class? Wasn't sure the best fit.

**Comment by melix** [comment]
Adding to `io.micronaut.gradle.LambdaNativeImageSpec` probably makes sense, thanks!

**Review by melix — APPROVED** [review]

**Pull request merged**
