### PR TITLE
Add Kotest5 as a testRuntime

### PR DESCRIPTION
**Pull request by timyates**
We desire to migrate from kotest 4 to kotest 5.  This PR adds a new testRuntime option
'kotest5' which injects the correct dependencies.

I couldn't find any tests for this, and we should add it as an option to launch once
this PR is accepted and released

See discussion here https://github.com/micronaut-projects/micronaut-starter/pull/1296#pullrequestreview-1008860774

### CODE REVIEW

**Review by melix — APPROVED** [review]

**Comment by timyates** [comment]
[The test seems to be failing on Java 8](https://ge.micronaut.io/s/riotba46x6uqo/tests/:functional-tests:test/io.micronaut.gradle.kotlin.Kotest5FunctionalTest/test%20kotest%205%20test%20runtime%20with%20id%20%22io.micronaut.application%22?anchor=e30&focused-exception-line=0-108&top-execution=1)...  I wonder if I'm pulling in something I shouldn't be, or if Kotest5 is just Java 11 only...

Pushed an `@IgnoreIf` to skip Java 8 for now...

**Comment by timyates** [comment]
Hmmm...  Native Image task spec seems to be failing with OOM errors

https://ge.micronaut.io/scans/tests?search.timeZoneId=Europe/London&tests.container=io.micronaut.gradle.NativeImageTaskSpec&tests.test=test%20build%20native%20image%20-%20custom%20name

@melix I don't believe it's this PR in particular that's at fault, as this is showing the same issue https://github.com/micronaut-projects/micronaut-gradle-plugin/actions/runs/2514658132

**Comment by melix** [comment]
This is fairly common on CI unfortunately, just restart the failing workflows.

**Comment by timyates** [comment]
5 attempts on the static analysis job

I wonder if we should just give gradle some more memory

**Comment by melix** [comment]
I don't think it's Gradle which needs more memory, it's native image:

```
GC warning: 38.0s spent in 7 GCs during the last stage, taking up 54.13% of the time.
              Please ensure more than 4.04GB of memory is available for Native Image
              to reduce GC overhead and improve image build time.
  Error: Image build request failed with exit status 137
```

The problem is that the agent has limited memory, and we have:
    - the main Gradle build
    - the build under test
    - native image

And that seems to be a bit much for the build agents :/

**Pull request merged**
