### PR TITLE
OpenAPI generator new properties

### PR DESCRIPTION
**Pull request by altro3**
Prepare for next micronaut-openapi release

### CODE REVIEW

**Comment by altro3** [comment]
@melix hi! Yeah, I'll finish tomorrow

**Comment by altro3** [comment]
@melix oh, the latest release 5.1.1 didn't include these changes :-(. I'm afraid we'll have to wait for the 5.2.0 release...

**Comment by melix** [comment]
Should be doable now that 5.2.0 is out.

**Comment by altro3** [comment]
@melix Yes, that's right, but you need to add a language selection. Now there is a generator for Kotlin. I'll try to do it this week

**Comment by melix** [comment]
This looks like a breaking change, right? There's now `forJavaServer` and `forKotlinServer`, instead of just `forServer`, so I guess older builds which use these will break. Was that change necessary?

**Comment by altro3** [comment]
@melix I just tried not to change the old structure and integrate support for the new generator with minimal changes

**Comment by altro3** [comment]
Generator settings for Kotlin and Java may differ. Yes, at the moment they coincide in this place, but in general, no one guarantees that this will not change later. The generators themselves for Java and Kotlin are absolutely not related to each other. They have different settings and different classes

**Comment by altro3** [comment]
Yes, by the way, how can this be a breaking change if nothing changes for the user and the settings through the plugin are done in the same way as before?

**Comment by melix** [comment]
Got it, but from what I see, openapi-generator has a breaking change. It would have been better to keep `forServer` as an alias for `forJavaServer`. Integrating such breaking changes will require bumping the major version of the plugin.

**Comment by altro3** [comment]
What do you suggest? Just add `forServer` with `@Deprecated` annotation, which call `forJavaServer` method inside?

And why we can't up major version of plugin?

**Comment by melix** [comment]
No you're right that it doesn't seem to break compatibility here since the mapping is done internally. I will checkout the branch locally and carefully review it, easier than GitHub. Note that we _can_ bump the plugin version but it's always a bit annoying because we maintain several branches.

**Comment by melix** [comment]
@altro3 I have fixed the Kotlin tests setup. However it seems that the Kotlin generator generates incorrect Kotlin code: the server tests are failing with a compile error. It is also possible that we need to properly setup the dependencies for Kotlin sources, I'm not sure yet.

**Comment by altro3** [comment]
@melix could you alsio update micronaut-openapi to version 6.2.0 ? @sdelamo released it right now. This version contains fixes for the latest known bugs. There's nothing else to fix for now

**Comment by altro3** [comment]
@melix I checked the generator. The code is correct, apparently, the dependencies really need to be fixed. Then I'll look at it tomorrow and then I can update micronaut-openapi to the latest version myself

**Comment by melix** [comment]
Ok, I'm confused because compilation fails on this line:
```kotlin
security = [
            SecurityRequirement(name = "petstore_auth", scopes = {"write:pets", "read:pets"})
        ]
```

with:

```
> Task :kaptGenerateStubsKotlin FAILED
e: file:///tmp/junit6466566742010923247/build/generated/openapi/generateServerOpenApiApis/src/main/kotlin/io/micronaut/openapi/api/PetApi.kt:51:79 Unexpected tokens (use ';' to separate expressions on the same line)
```

**Comment by altro3** [comment]
> Ok, I'm confused because compilation fails on this line:
> 
> ```kotlin
> security = [
>             SecurityRequirement(name = "petstore_auth", scopes = {"write:pets", "read:pets"})
>         ]
> ```
> 
> with:
> 
> ```
> > Task :kaptGenerateStubsKotlin FAILED
> e: file:///tmp/junit6466566742010923247/build/generated/openapi/generateServerOpenApiApis/src/main/kotlin/io/micronaut/openapi/api/PetApi.kt:51:79 Unexpected tokens (use ';' to separate expressions on the same line)
> ```

I'll check or fix it tomorrow. Maybe it's really bug

**Comment by altro3** [comment]
I think problem is here - `{"write:pets", "read:pets"}`, must be `["write:pets", "read:pets"]`

**Comment by melix** [comment]
yeah that's why I'm confused, for me there's a bug in the generator

**Comment by altro3** [comment]
Yeah, I agree. Will fix it tomorrow

**Comment by altro3** [comment]
@melix could you check what is wrong now? I fixed generator bug

**Comment by altro3** [comment]
@lucjross-favor Hi! thanks for help. Yes, I saw this message in logs, but the problem is that this message has nothing to do with the generator. Those. This is a potential bug in micronaut-openapi (in the swagger file generator by code), but this has nothing to do with the bug with micronaut-openapi-generator - the code generator by swagger file. So I don't think that's the problem

**Comment by altro3** [comment]
@melix could you help?

**Comment by melix** [comment]
I think the error is unrelated here. The test resources tests put high load on agents and sometimes it fails. Also 3rd party branches cannot publish build scans.

**Comment by altro3** [comment]
@melix yes, yes

**Pull request merged**
