### PR TITLE
Add support for optimizing lambdas

### PR DESCRIPTION
**Pull request by melix**
This commit adds initial support for optimizing Micronaut libraries,
in particular functions. For now tests limited to lambdas, but
deployment is **not** tested yet.

### CODE REVIEW

**Comment by graemerocher** [comment]
We need variations of `buildLambdaZip` and `buildNativeLambda` that build the optimized versions. See https://www.youtube.com/watch?v=76JPU9cyuLk for demos of usage

**Comment by melix** [comment]
Will take a look, thanks. One question I have is regarding deployment of the native version. Currently the function is a _library_, which means that `native-image` will generate a `.so`. This means, as far as I understand, that we need a custom runtime to be able to run this, no? All guides I have found so far workaround the problem by creating an _application_ instead.

**Comment by graemerocher** [comment]
A custom runtime is used to deploy Lambda with native image. That is why we set this here https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/1706100deb116b89298bb31f3c2093afa7bdf669/src/main/java/io/micronaut/gradle/graalvm/MicronautGraalPlugin.java#L75

**Comment by melix** [comment]
But isn't this custom runtime needing an actual `main()` method, so an `application`?

**Comment by graemerocher** [comment]
Correct

**Comment by melix** [comment]
With AOT 1.0.0-M6 this should now work properly.

**Review by graemerocher — APPROVED** [review]

**Pull request merged**
