### PR TITLE
Add support for overriding some Micronaut module versions

### LINKED ISSUE #689: In Micronaut Framework 4.x allow user to define micronaut.coreVersion
In Micronaut framework 4, a [Micronaut Release is a release of Platform and starter](https://github.com/micronaut-projects/micronaut-platform/discussions/200). 

In Micronaut versions prior to 3, [using a Snapshot](https://docs.micronaut.io/latest/guide/#usingsnapshots) meant using a core snapshot. Modules had a fixed version.  

In Micronaut 4, when a user sets, `micronaut.version`, they are setting the version of Micronaut Platform BOM. Thus, they will not be using any snapshot for core. 

Moreover, the Micronaut Gradle plugin adds [dependencies](https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/master/minimal-plugin/src/main/java/io/micronaut/gradle/MicronautRuntimeDependencies.java#L29-L55) automatically to the user classpath. 

Those dependencies are from `test`, `gcp`, `aws`, `servlet`, `azure`, `oracle-cloud`, and `core`. 

It would be good if the user could override via the micronaut extension those versions. 

E.g. if you have in you `gradle.properties`,  `micronautVersion=4.0.1`. You could set: 

```groovy
micronaut {
    coreVersion = '4.0.2-SNAPSHOT'
    awsVersion = '5.2.0-SNAPSHOT'
}
```

and the Micronaut Gradle plugin will add under the hood: 

```groovy
`Implementation("io.micronaut.aws:micronaut-aws-whatever:5.2.0-SNAPSHOT`")
`Implementation("io.micronaut:micronaut-inject.java:4.0.2-SNAPSHOT`")
```

[Context of this issue](https://github.com/micronaut-projects/micronaut-platform/pull/201#issuecomment-1503073331)

### PR DESCRIPTION
**Pull request by melix**
This commit adds the ability to override the version of some dependencies which are automatically added by the Gradle plugin. For example, a `micronautCoreVersion` property in gradle.properties file will override the default micronaut core version.

There are 2 places where the version can be overriden. Either via the DSL, under the `micronaut` extension, e.g:

```
micronaut {
   dataVersion.set("...")
}
```

or via `gradle.properties` in which case the version is prefixed with `micronaut`, e.g `micronautDataVersion`.

The modules for which we added version overrides are all modules which have automatic dependencies:

  - core
  - aws
  - azure
  - data
  - gcp
  - http_netty
  - jaxrs
  - oraclecloud
  - security
  - servlet
  - validation

Note that because of https://github.com/gradle/gradle/issues/24719, the DSL doesn't let us use the `=` operator, so one has to write `.set("...")`. This problem is not present with the experimental Kotlin DSL assignment operator in Gradle 8.1.

Closes #689

### CODE REVIEW

**Review by sdelamo — CHANGES_REQUESTED** [review]
Can you add documentation as well?

**Comment by melix** [comment]
I will submit another PR which improves on this one to add support for overriding via version catalogs. I will document the feature in that PR. Note that in the process I discovered a "bug" in this one, in the sense that `httpNetty` shouldn't have its own override, since it's bound to the core version. That other PR will fix it, so supercede this one.

**Comment by sdelamo** [comment]
> I will submit another PR which improves on this one to add support for overriding via version catalogs. I will document the feature in that PR. Note that in the process I discovered a "bug" in this one, in the sense that `httpNetty` shouldn't have its own override, since it's bound to the core version. That other PR will fix it, so supercede this one.

do you want me to review this one or wait for the next one?

**Comment by melix** [comment]
The next one is going to build on top of this one, so for you it's easier to review this one, then the next one, but I won't merge this one, only the next.

**Comment by melix** [comment]
Superceded by #694

**Pull request closed without merging**
