### PR TITLE
Add KSP support and re-enable Kotlin tests

### PR DESCRIPTION
**Pull request by graemerocher**
Adds support for configuring KSP including handling the new `inject-kotlin` module and configuring the `ksp` and `kspTest` classpaths

### CODE REVIEW

**Comment by graemerocher** [comment]
hmm not sure why these fail on CI but pass locally 🤔

**Comment by melix** [comment]
I'm seeing failures locally too, I will investigate:

```
* What went wrong:
org/jetbrains/kotlin/gradle/dsl/KaptArguments
> org.jetbrains.kotlin.gradle.dsl.KaptArguments

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
java.lang.NoClassDefFoundError: org/jetbrains/kotlin/gradle/dsl/KaptArguments
```

**Comment by melix** [comment]
So I have fixed the failing tests, and in the process, I added a test with the `kotest` test runtime. However, it seems that the KSP plugin doesn't work with kotest.

If you uncomment the following lines: https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/0222d20eec0d41783df1d97468d4bd8417968413/functional-tests/src/test/groovy/io/micronaut/gradle/kotlin/Kotest5FunctionalTest.groovy#L98-L99

then you will see the tests failing with:

```
> Task :kspTestKotlin FAILED
e: [ksp] java.lang.IllegalStateException: Cannot map null value in: com.example.$ExampleTest$Definition$Reference
	at io.micronaut.inject.annotation.AnnotationMetadataWriter.pushValue(AnnotationMetadataWriter.java:553)
	at io.micronaut.inject.annotation.AnnotationMetadataWriter.lambda$pushValue$8(AnnotationMetadataWriter.java:588)
	at io.micronaut.inject.writer.AbstractClassFileWriter.pushStoreInArray(AbstractClassFileWriter.java:1055)
	at io.micronaut.inject.annotation.AnnotationMetadataWriter.pushValue(AnnotationMetadataWriter.java:587)
	at io.micronaut.inject.annotation.AnnotationMetadataWriter.lambda$pushValue$10(AnnotationMetadataWriter.java:658)
	at io.micronaut.inject.writer.AbstractClassFileWriter.pushStringMapOf(AbstractClassFileWriter.java:1739)
	at io.micronaut.inject.annotation.AnnotationMetadataWriter.pushValue(AnnotationMetadataWriter.java:658)
	at io.micronaut.inject.annotation.AnnotationMetadataWriter.lambda$pushValue$9(AnnotationMetadataWriter.java:610)
	at io.micronaut.inject.writer.AbstractClassFileWriter.pushStoreInArray(AbstractClassFileWriter.java:1055)
	at io.micronaut.inject.annotation.AnnotationMetadataWriter.pushValue(AnnotationMetadataWriter.java:609)
	at io.micronaut.inject.annotation.AnnotationMetadataWriter.lambda$pushCreateAnnotationData$6(AnnotationMetadataWriter.java:541)
	at io.micronaut.inject.writer.AbstractClassFileWriter.pushStringMapOf(AbstractClassFileWriter.java:1739)
	at io.micronaut.inject.annotation.AnnotationMetadataWriter.lambda$pushCreateAnnotationData$7(AnnotationMetadataWriter.java:540)
	at io.micronaut.inject.writer.AbstractClassFileWriter.pushStringMapOf(AbstractClassFileWriter.java:1739)
	at io.micronaut.inject.annotation.AnnotationMetadataWriter.pushCreateAnnotationData(AnnotationMetadataWriter.java:539)
	at io.micronaut.inject.annotation.AnnotationMetadataWriter.instantiateInternal(AnnotationMetadataWriter.java:468)
	at io.micronaut.inject.annotation.AnnotationMetadataWriter.instantiateNewMetadata(AnnotationMetadataWriter.java:265)
	at io.micronaut.inject.writer.AbstractAnnotationMetadataWriter.initializeAnnotationMetadata(AbstractAnnotationMetadataWriter.java:188)
	at io.micronaut.inject.writer.AbstractAnnotationMetadataWriter.writeAnnotationMetadataStaticInitializer(AbstractAnnotationMetadataWriter.java:168)
	at io.micronaut.inject.writer.AbstractAnnotationMetadataWriter.writeAnnotationMetadataStaticInitializer(AbstractAnnotationMetadataWriter.java:132)
	at io.micronaut.inject.writer.BeanDefinitionReferenceWriter.generateClassBytes(BeanDefinitionReferenceWriter.java:280)
	at io.micronaut.inject.writer.BeanDefinitionReferenceWriter.accept(BeanDefinitionReferenceWriter.java:121)
	at io.micronaut.kotlin.processing.beans.BeanDefinitionProcessor.processBeanDefinitions(BeanDefinitionProcessor.kt:152)
	at io.micronaut.kotlin.processing.beans.BeanDefinitionProcessor.finish(BeanDefinitionProcessor.kt:103)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$10$1.invoke(KotlinSymbolProcessingExtension.kt:322)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$10$1.invoke(KotlinSymbolProcessingExtension.kt:321)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:390)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:321)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:123)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:99)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:257)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:42)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:248)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:88)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:47)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:167)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:53)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:101)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:47)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1645)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

I am not sure if we're supposed to support this, and if so, if it's a bug in our KSP support or that the test is not setup correctly.

**Comment by graemerocher** [comment]
Probably a bug will look when I get back

**Pull request merged**
