### PR TITLE
Fix native build on Windows

### PR DESCRIPTION
**Pull request by andriy-dmytruk**
Fixes native build on Windows. The fixes are related to the fact that the separator is `\` on Windows:

### CODE REVIEW

**Comment by timyates** [comment]
@andriy-dmytruk Don't forget to add this to a Project, or it may get missed from the release train 🚂

**Comment by andriy-dmytruk** [comment]
@timyates Thanks for ping. I added it to 4.2.0 release. Is it right? It is first time I am adding anything in projects🤨

**Comment by timyates** [comment]
🤔 if it's a bugfix with no breaking changes, I guess it could go in 4.0.6?

**Comment by andriy-dmytruk** [comment]
Cannot find it there for some reason 🤨

**Review by melix — APPROVED** [review]

**Pull request merged**
