### PR TITLE
Add support for configuring target working directory

### LINKED ISSUE #402: Micronaut Docker plugin allows to override WORKDIR
### Feature description

Add ability to change WORKDIR for Micronaut Docker image instead of hard-coded `/home/app`.
Currently, path for layers is hardcoded in `setupResources` (See [code](https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/374a4ba6f4a1efbe3e8fce73b8e36cb64161de83/docker-plugin/src/main/java/io/micronaut/gradle/docker/MicronautDockerfile.java#L175)).

I want to add a custom user `myuser` and put dependencies into `/home/myuser`:
```
FROM openjdk:17-alpine
WORKDIR /home/myuser
RUN adduser -u 2000 -D myuser -s /bin/sh myuser
COPY layers/libs /home/myuser/libs
COPY layers/classes /home/myuser/classes
COPY layers/resources /home/myuser/resources
COPY layers/application.jar /home/myuser/application.jar
USER 2000
ENTRYPOINT ["java", "-jar", "/home/myuser/application.jar"]
```

`workingDir` just add another command `WORKDIR` but the hardcoded path is not updated.

The following code:
```
dockerfile {
        baseImage.set("openjdk:17-alpine")
        runCommand("myuser -u 2000 -D myuser -s /bin/sh myuser")
        workingDir("/home/myuser")
        exposedPorts.set(emptyList())
        user("2000")
        entryPoint("java", "-jar", "/home/myuser/application.jar")
    }
```
generates: 
```
FROM openjdk:17-alpine
WORKDIR /home/app
COPY layers/libs /home/app/libs
COPY layers/classes /home/app/classes
COPY layers/resources /home/app/resources
COPY layers/application.jar /home/app/application.jar
RUN myuser -u 2000 -D myuser -s /bin/sh myuser
WORKDIR /home/myuser
USER 2000
ENTRYPOINT ["java", "-jar", "/home/myuser/application.jar"]
```

As an workaround I use:
```
dockerfile {
        baseImage.set("openjdk:17-alpine")
        runCommand("adduser -u 2000 -D myuser -s /bin/sh myuser")
        runCommand("mv /home/app/* /home/myuser/") // FIXME: remove it once Micronaut remove hardcoded /home/app
        workingDir("/home/myuser")
        exposedPorts.set(emptyList())
        user("2000")
        entryPoint("java", "-jar", "/home/myuser/application.jar")
    }
```

```
FROM openjdk:17-alpine
WORKDIR /home/app
COPY layers/libs /home/app/libs
COPY layers/classes /home/app/classes
COPY layers/resources /home/app/resources
COPY layers/application.jar /home/app/application.jar
RUN adduser -u 2000 -D myuser -s /bin/sh myuser
RUN mv /home/app/* /home/myuser/
WORKDIR /home/myuser
USER 2000
ENTRYPOINT ["java", "-jar", "/home/myuser/application.jar"]
```
but it breaks whole the point of the layered build.

### PR DESCRIPTION
**Pull request by melix**
This commit adds the ability to choose in which target directory
the application will be put inside a docker container.

Fixes #402

### CODE REVIEW

**Comment by alvarosanchez** [comment]
Don't you need to add the property to the documentation?

**Comment by melix** [comment]
We don't document individual properties in the docs yet.

**Comment by alvarosanchez** [comment]
So how are users supposed to know they can use that?

**Comment by melix** [comment]
It's in the reference API.

**Review by alvarosanchez — APPROVED** [review]
Honestly, the API reference is far from ideal to document the different options.

I understand, however, that it is a larger problem and beyond the scope of this PR.

Can we at least create a task to document all possible options (with their default values) and schedule it for the next release, please?

**Comment by melix** [comment]
I don't think it's reasonable to schedule this for the next release. There are many configuration options, lots of them inherited from other plugins that we use. The docs are not ideal, but Gradle users are used to using the API reference as well as IDE completion. So I'm not against improving docs of course, but I don't think this deserves high priority compared to other things we have to do.

**Pull request merged**
