### PR TITLE
Micronaut-openapi 6.7.0

### LINKED ISSUE #949: clientId not set on generated class
### Expected Behavior

given 
```
micronaut {
    openapi {
        version = "6.6.2"
        client(file("src/main/resources/taizo-feedsmanager-v1-openapi.yaml")) {
            ...
            clientId = "my-client"
        }
    }
}
```
I would expect the API class to have:
```
@Client("my-client")
public interface MyApi {
  ...
```

### Actual Behaviour

The API class has:
```
@Client("${openapi-micronaut-client-base-path}")
public interface MyApi {
  ...
```

### Steps To Reproduce

Create or use an exiting opanapi file.
Configure gradle:
```
micronaut {
    openapi {
        version = "6.6.2"
        client(file("src/main/resources/myapi-v1-openapi.yaml")) {
            apiPackageName = "myapi.client.models"
            modelPackageName = "myapi.client.api"
            useOptional = true
            useReactive = false
            clientId = "my-client"
        }
    }
}
```
Run `./gradlew generateClientOpenApiApis`

### Environment Information

MacOS
java 21-tem
Micronaut 4.3.1
Micronaut Gradle Plugin 4.3.3

### Example Application

_No response_

### Version

4.3.1

### PR DESCRIPTION
**Pull request by altro3**
Added test to clientId generator property

Fixed #949

### CODE REVIEW

**Comment by altro3** [comment]
Wait micronaut-openapi 6.6.3 release

**Comment by altro3** [comment]
don't merge it pls, wait openapi 6.7.0

**Comment by timyates** [comment]
@altro3 this pr only makes a single change

https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/950/files#diff-0d8feb3d2e60a4085c22391e83952def203f6d69a5ae209e04b1886d52a971f9

(plus 2 tests)

Should it be closed then?

Or should I revert the 6.6.3 update?

**Comment by altro3** [comment]
I'll change this PR to 6.7.0. In 6.7.0 will be one more property. Need to add it here. I'll do it timorrow

**Comment by timyates** [comment]
@altro3 should I revert [the 6.6.3 update](https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/961)?

**Comment by altro3** [comment]
It desn't matter. With 6.6.3 all works fine, but as I remeber I've added one more property for configuration.  And all that is not completed is that you will not be able to set this property through the plugin.

**Comment by timyates** [comment]
Ok, I'll leave this PR in draft for now, but release 4.3.5 of the plugin with 6.6.3 of the openapi generator

**Comment by sdelamo** [comment]
Lets go ahead with the patch release of the gradle plugin and then we can make a minor release with the minor of open api

**Comment by altro3** [comment]
@timyates @melix All ready to review and merge

**Review by melix — APPROVED** [review]

**Pull request merged**
